import fs from 'node:fs';
import assert from 'node:assert/strict';
const read=p=>fs.readFileSync(p,'utf8');
const pkg=JSON.parse(read('package.json'));
assert.equal(pkg.devDependencies.typescript,'7.0.2');
assert.equal(pkg.devDependencies['@playwright/test'],'1.62.1');
const ts=JSON.parse(read('tsconfig.json'));assert.equal(ts.compilerOptions.strict,true);assert.equal(ts.compilerOptions.outDir,'assets/ts');
for(const p of ['assets/ts/public/date.js','assets/ts/pwa/runtime.js','assets/ts/analytics/powerbi-engine.js','assets/ts/charts/performance.js']){assert.ok(fs.existsSync(p),`${p} debe generarse con TypeScript`)}
const manifest=JSON.parse(read('manifest.webmanifest'));assert.equal(manifest.id,'./');assert.equal(manifest.start_url,'./');assert.equal(manifest.prefer_related_applications,false);assert.ok(manifest.shortcuts.some(x=>x.url==='./admin.html'));assert.ok(manifest.icons.some(x=>x.sizes==='192x192'&&x.type==='image/png'));assert.ok(manifest.icons.some(x=>x.sizes==='512x512'&&x.type==='image/png'));assert.ok(fs.existsSync('assets/icons/campamento-192.png'));assert.ok(fs.existsSync('assets/icons/campamento-512.png'));
const sw=read('service-worker.js');assert.match(sw,/campamento-shell-5\.6\.1-modern\.12-r5-operational-v1/);assert.match(sw,/SKIP_WAITING/);assert.match(sw,/url\.origin!==self\.location\.origin/);assert.doesNotMatch(sw,/supabase\.co/);assert.match(sw,/assets\/ts\/public\/date\.js/);assert.match(sw,/campamento-512\.png/);
const app4=read('assets/app-4.js');assert.match(app4,/semantic-model-runtime\.js\?v=20260902-r5-movement-lifecycle-v1/);assert.ok(app4.indexOf('resilience-runtime.js')<app4.indexOf('powerbi-engine.js'));assert.match(app4,/assets\/ts\/pwa\/runtime\.js/);
const pwaTs=read('src/pwa/runtime.ts');assert.match(pwaTs,/activateRequested/);assert.match(pwaTs,/activateRequested&&!reloading/);
const chartTs=read('src/charts/performance.ts');assert.doesNotMatch(chartTs,/MutationObserver/);assert.match(chartTs,/IntersectionObserver/);
const index=read('index.html');assert.match(index,/rel="manifest" href="manifest\.webmanifest"/);assert.match(index,/assets\/ts\/public\/date\.js/);assert.doesNotMatch(index,/assets\/public-date\.js/);
const workflow=read('.github/workflows/validate-modernization.yml');assert.match(workflow,/playwright install --with-deps chromium/);assert.match(workflow,/npm run typecheck/);assert.match(workflow,/analytics-engine-smoke\.mjs/);
const pages=read('.github/workflows/pages.yml');assert.match(pages,/npm run build/);assert.match(pages,/modernization-smoke\.mjs/);assert.match(pages,/analytics-engine-smoke\.mjs/);
const admin=read('admin.html');
assert.match(index,/<div class="public-date" role="group" aria-label="Fecha de consulta">/);
assert.match(index,/<div class="public-steps" role="group" aria-label="Pasos de la consulta">/);
assert.match(index,/<div id="workerLookupResult" class="result-zone public-result" role="status" aria-live="polite" aria-atomic="false" aria-label="Resultado de la consulta"><\/div>/);
assert.doesNotMatch(index,/<div class="public-date" aria-label=/);
assert.doesNotMatch(index,/<div class="public-steps" aria-label=/);
assert.match(admin,/<div id="adminLoginScreen" class="login-screen" role="main">/);
console.log('R6C accessibility contracts: OK');
console.log('Modernización smoke: OK');
