DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='camp_app') THEN CREATE ROLE camp_app LOGIN PASSWORD '5GXgu_TG0AZpY7AenLgvP7LYDamaEgWt9lrYYw92X7A'; END IF; END $$;
GRANT CONNECT ON DATABASE postgres TO camp_app;
GRANT USAGE ON SCHEMA public TO camp_app;
GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA public TO camp_app;
GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA public TO camp_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT,INSERT,UPDATE,DELETE ON TABLES TO camp_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE,SELECT ON SEQUENCES TO camp_app;;
