create table if not exists public.backup_restore_tests (
  id bigint generated by default as identity primary key,
  tested_at timestamptz not null default now(),
  backup_schema text not null,
  status text not null check (status in ('OK','ERROR')),
  tables_checked integer not null default 0,
  source_rows bigint not null default 0,
  restored_rows bigint not null default 0,
  duration_ms integer not null default 0,
  profile text not null default 'ADMINISTRADOR',
  detail jsonb not null default '{}'::jsonb
);
create index if not exists backup_restore_tests_tested_at_idx on public.backup_restore_tests(tested_at desc);
alter table public.backup_restore_tests enable row level security;
revoke all on public.backup_restore_tests from anon, authenticated;
grant select, insert on public.backup_restore_tests to service_role;
grant usage, select on sequence public.backup_restore_tests_id_seq to service_role;

create or replace function public.run_backup_restore_test(p_backup_schema text default 'backup_pre_integridad_20260828', p_profile text default 'ADMINISTRADOR')
returns jsonb
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  t text;
  tables text[] := array['workers','bed_inventory','reservations','movements','bed_blocks','daily_snapshots','daily_capacity','settings','import_history','consultation_log','operational_actions','master_plan_events','what_if_scenarios','audit_log'];
  src bigint;
  dst bigint;
  total_src bigint := 0;
  total_dst bigint := 0;
  checked_count integer := 0;
  started timestamptz := clock_timestamp();
  details jsonb := '{}'::jsonb;
  safe_profile text := case when upper(coalesce(p_profile,'')) in ('ADMINISTRADOR','OPERADOR','JEFATURA') then upper(p_profile) else 'ADMINISTRADOR' end;
  result_status text := 'OK';
  result_id bigint;
begin
  if p_backup_schema !~ '^backup_[a-z0-9_]+$' then
    raise exception 'Esquema de respaldo inválido';
  end if;
  if not exists(select 1 from information_schema.schemata where schema_name=p_backup_schema) then
    raise exception 'No existe el esquema de respaldo %', p_backup_schema;
  end if;

  foreach t in array tables loop
    if not exists(select 1 from information_schema.tables where table_schema=p_backup_schema and table_name=t) then
      details := details || jsonb_build_object(t, jsonb_build_object('status','MISSING'));
      result_status := 'ERROR';
      continue;
    end if;
    execute format('select count(*) from %I.%I',p_backup_schema,t) into src;
    execute format('drop table if exists pg_temp.%I', '_restore_test_'||t);
    execute format('create temporary table %I on commit drop as table %I.%I', '_restore_test_'||t,p_backup_schema,t);
    execute format('select count(*) from pg_temp.%I', '_restore_test_'||t) into dst;
    checked_count := checked_count + 1;
    total_src := total_src + src;
    total_dst := total_dst + dst;
    if src <> dst then result_status := 'ERROR'; end if;
    details := details || jsonb_build_object(t, jsonb_build_object('source',src,'restored',dst,'status',case when src=dst then 'OK' else 'ERROR' end));
  end loop;

  insert into public.backup_restore_tests(backup_schema,status,tables_checked,source_rows,restored_rows,duration_ms,profile,detail)
  values(p_backup_schema,result_status,checked_count,total_src,total_dst,greatest(0,round(extract(epoch from (clock_timestamp()-started))*1000)::int),safe_profile,details)
  returning id into result_id;

  return jsonb_build_object('id',result_id,'tested_at',now(),'backup_schema',p_backup_schema,'status',result_status,'tables_checked',checked_count,'source_rows',total_src,'restored_rows',total_dst,'duration_ms',greatest(0,round(extract(epoch from (clock_timestamp()-started))*1000)::int),'detail',details);
end;
$$;

revoke all on function public.run_backup_restore_test(text,text) from public, anon, authenticated;
grant execute on function public.run_backup_restore_test(text,text) to service_role;
comment on function public.run_backup_restore_test(text,text) is 'Prueba lógica aislada: restaura tablas del esquema de respaldo en tablas temporales, compara conteos y no modifica producción.';;
