-- R3_SCHEMA_FOUNDATIONS
-- Release class: EXPAND
--
-- Adds persistence foundations only.
-- No R4-R7 runtime cutover occurs here.
--
-- ROLLBACK CLASSIFICATION:
-- Compatibility rollback. Additive structures are retained until
-- dependent releases have been retired. No historical identity,
-- movement lifecycle or snapshot provenance is fabricated.

-- ============================================================
-- RESERVATION MEMBERS
--
-- workers is intentionally NOT referenced.
-- workers is replaceable operational state sourced from Excel.
-- ============================================================

create table if not exists public.reservation_members (
  id bigint generated by default as identity primary key,

  reservation_id bigint not null
    references public.reservations(id)
    on delete cascade,

  rut text not null,

  person_name text,

  created_at timestamptz not null
    default now(),

  constraint reservation_members_reservation_rut_key
    unique (reservation_id, rut),

  constraint reservation_members_rut_canonical_check
    check (
      rut = upper(rut)
      and rut ~ '^[0-9]{5,9}-[0-9K]$'
    )
);

alter table public.reservation_members
  enable row level security;

revoke all
  on table public.reservation_members
  from public;

do $r3_security$
declare
  v_sequence text;
begin
  if exists (
    select 1
    from pg_roles
    where rolname = 'anon'
  ) then
    execute
      'revoke all on table public.reservation_members from anon';
  end if;

  if exists (
    select 1
    from pg_roles
    where rolname = 'authenticated'
  ) then
    execute
      'revoke all on table public.reservation_members from authenticated';
  end if;

  if exists (
    select 1
    from pg_roles
    where rolname = 'service_role'
  ) then
    execute
      'grant select, insert, update, delete on table public.reservation_members to service_role';

    v_sequence :=
      pg_get_serial_sequence(
        'public.reservation_members',
        'id'
      );

    if v_sequence is not null then
      execute format(
        'grant usage, select on sequence %s to service_role',
        v_sequence::regclass
      );
    end if;
  end if;
end;
$r3_security$;

-- ============================================================
-- MOVEMENT LIFECYCLE
--
-- Existing and legacy-runtime rows remain explicitly unresolved.
-- They are never inferred to PROGRAMADO.
-- ============================================================

alter table public.movements
  add column if not exists lifecycle_status text
  not null
  default 'LEGACY_UNRESOLVED';

alter table public.movements
  add column if not exists executed_at timestamptz;

alter table public.movements
  add column if not exists cancelled_at timestamptz;

do $r3_movement$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.movements'::regclass
      and conname =
        'movements_lifecycle_status_r3_check'
  ) then

    alter table public.movements
      add constraint
        movements_lifecycle_status_r3_check
      check (
        lifecycle_status in (
          'PROGRAMADO',
          'EJECUTADO',
          'CANCELADO',
          'LEGACY_UNRESOLVED'
        )
      )
      not valid;

  end if;
end;
$r3_movement$;

-- ============================================================
-- DAILY SNAPSHOT PROVENANCE
--
-- Existing snapshots receive only an explicit unresolved marker.
-- No source, fingerprint, import or revision is guessed.
-- ============================================================

alter table public.daily_snapshots
  add column if not exists
    provenance_status text
  not null
  default 'LEGACY_UNRESOLVED';

alter table public.daily_snapshots
  add column if not exists
    capacity_source text;

alter table public.daily_snapshots
  add column if not exists
    operational_universe_count integer;

alter table public.daily_snapshots
  add column if not exists
    operational_universe_fingerprint text;

alter table public.daily_snapshots
  add column if not exists
    source_import_id bigint;

alter table public.daily_snapshots
  add column if not exists
    source_operational_revision bigint;

alter table public.daily_snapshots
  add column if not exists
    semantic_version text;

alter table public.daily_snapshots
  add column if not exists
    provenance_version text;

do $r3_snapshot$
begin

  if not exists (
    select 1
    from pg_constraint
    where conrelid =
      'public.daily_snapshots'::regclass
      and conname =
        'daily_snapshots_universe_count_r3_check'
  ) then

    alter table public.daily_snapshots
      add constraint
        daily_snapshots_universe_count_r3_check
      check (
        operational_universe_count is null
        or operational_universe_count >= 0
      )
      not valid;

  end if;

  if not exists (
    select 1
    from pg_constraint
    where conrelid =
      'public.daily_snapshots'::regclass
      and conname =
        'daily_snapshots_revision_r3_check'
  ) then

    alter table public.daily_snapshots
      add constraint
        daily_snapshots_revision_r3_check
      check (
        source_operational_revision is null
        or source_operational_revision >= 0
      )
      not valid;

  end if;

end;
$r3_snapshot$;

-- ============================================================
-- DAILY CAPACITY INTEGRITY FOUNDATION
--
-- NOT VALID avoids historical table validation during EXPAND.
-- PostgreSQL still enforces the condition for new/changed rows.
-- R4 performs the actual Capacity V1 semantic cutover.
-- ============================================================

do $r3_capacity$
begin

  if not exists (
    select 1
    from pg_constraint
    where conrelid =
      'public.daily_capacity'::regclass
      and conname =
        'daily_capacity_capacity_nonnegative_r3_check'
  ) then

    alter table public.daily_capacity
      add constraint
        daily_capacity_capacity_nonnegative_r3_check
      check (capacity >= 0)
      not valid;

  end if;

end;
$r3_capacity$;

-- End R3_SCHEMA_FOUNDATIONS.
-- Existing daily_capacity_default / 132 behavior is untouched.
