-- ============================================================================
-- GARPI P2.6D — REQUEST / CORRELATION PROVENANCE
-- RELEASE TYPE : EXPAND / HARDEN
-- RUNTIME CUTOVER: NO
-- DATA BACKFILL: NO
--
-- Purpose:
--   Enrich new audit_log rows with request-scoped provenance carried by
--   PostgREST request headers.
--
-- Grounded provenance only:
--   request_id     = generated by trusted Edge request boundary
--   correlation_id = existing client cid when present and valid
--
-- No legacy provenance is fabricated.
-- No audit_log columns are added.
-- No typed RPC signature is changed.
-- ============================================================================

create or replace function public.p2_enrich_audit_request_provenance()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog
as $p2_request_provenance$
declare
    v_headers_raw text;
    v_headers jsonb;

    v_request_id text;
    v_correlation_id text;
begin
    if new.details is null
       or pg_catalog.jsonb_typeof(new.details) <> 'object'
    then
        new.details := '{}'::jsonb;
    end if;

    v_headers_raw :=
        nullif(
            pg_catalog.current_setting(
                'request.headers',
                true
            ),
            ''
        );

    if v_headers_raw is null then
        return new;
    end if;

    begin
        v_headers :=
            v_headers_raw::jsonb;
    exception
        when others then
            -- Request provenance is additive hardening.
            -- An unavailable/unparseable context must never invent values.
            return new;
    end;

    v_request_id :=
        nullif(
            pg_catalog.btrim(
                coalesce(
                    v_headers ->> 'x-request-id',
                    ''
                )
            ),
            ''
        );

    v_correlation_id :=
        nullif(
            pg_catalog.btrim(
                coalesce(
                    v_headers ->> 'x-correlation-id',
                    ''
                )
            ),
            ''
        );

    if v_request_id is not null then
        if v_request_id !~ '^[A-Za-z0-9._:-]{1,128}$' then
            v_request_id := null;
        else
            v_request_id :=
                pg_catalog.left(
                    v_request_id,
                    128
                );
        end if;
    end if;

    if v_correlation_id is not null then
        if v_correlation_id !~ '^[A-Za-z0-9._:-]{1,128}$' then
            v_correlation_id := null;
        else
            v_correlation_id :=
                pg_catalog.left(
                    v_correlation_id,
                    128
                );
        end if;
    end if;

    if v_request_id is null
       and v_correlation_id is null
    then
        return new;
    end if;

    -- Trusted request context wins over any same-named keys that an
    -- application semantic event may have supplied inside details.
    new.details :=
        new.details
        ||
        pg_catalog.jsonb_strip_nulls(
            pg_catalog.jsonb_build_object(
                'request_id',
                v_request_id,
                'correlation_id',
                v_correlation_id
            )
        );

    return new;
end
$p2_request_provenance$;


revoke all
    on function public.p2_enrich_audit_request_provenance()
    from public;


do $p2_request_provenance_acl$
declare
    v_role text;
begin
    foreach v_role in array array[
        'anon',
        'authenticated',
        'service_role',
        'camp_app',
        'replit_app'
    ]
    loop
        if exists (
            select 1
            from pg_catalog.pg_roles
            where rolname = v_role
        ) then
            execute pg_catalog.format(
                'revoke execute on function public.p2_enrich_audit_request_provenance() from %I',
                v_role
            );
        end if;
    end loop;
end
$p2_request_provenance_acl$;


drop trigger if exists audit_log_p2_request_provenance_bi
    on public.audit_log;


create trigger audit_log_p2_request_provenance_bi
before insert
on public.audit_log
for each row
execute function public.p2_enrich_audit_request_provenance();


comment on function public.p2_enrich_audit_request_provenance() is
    'GARPI P2.6D audit provenance enrichment from transaction-scoped PostgREST request headers. Adds grounded request_id/correlation_id to audit_log.details without fabricating absent legacy context.';