DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'campamento_app') THEN CREATE ROLE campamento_app LOGIN PASSWORD 'SZzqfDytlAZS7IqjkYNMUOu6VyEk8SLu'; END IF; END $$;
GRANT USAGE ON SCHEMA public TO campamento_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO campamento_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO campamento_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO campamento_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO campamento_app;;
